name: spawn_dart
description: A starting point for Dart libraries or applications.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.1.3

# Add regular dependencies here.
dependencies:
  fixnum: ^1.1.0
  googleapis_auth: ^1.4.1
  grpc: ^3.2.4
  logger: ^2.0.2+1
  meta: ^1.10.0
  optional: ^6.1.0+1
  protobuf: ^3.1.0
  shelf: ^1.4.0
  shelf_router: ^1.1.0

dev_dependencies:
  http: ^1.1.0
  lints: ^2.0.0
  test: ^1.21.0
  test_process: ^2.1.0
