name: spawn_app_example
description: A sample of spawn dart application.
version: 1.0.0
publish_to: none

environment:
  sdk: ^3.1.3

dependencies:
  spawn_dart:
    path: ../../

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0
